# Generated by Django 3.1.7 on 2021-03-25 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='socialaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='socialaccounts', to='socialaccount.socialaccount'),
        ),
    ]
