# Generated by Django 3.1.7 on 2021-03-25 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='socialaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relationships', to='socialaccount.socialaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('sender', 'receiver', 'socialaccount')},
        ),
    ]
